### ISSUE TITLE
Rhino usage warning: Missed Context.javaToJS() conversion

### ISSUE THREAD

**Issue by TheDeveloper** [elastic/elasticsearch-lang-javascript#26]
I'm using a JS script to process some properties on upsert. It appears that when the param passed to the script is a JS object containing other objects, those objects are not properly converted to JS types, and Rhino throws a warning in the elasticsearch log:

```
RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
Rhino runtime detected object { /** lots of properties here **/ } of class java.util.LinkedHashMap where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.
```

When enumerating nested objects in the script, they are not proper JS objects:

``` javascript
// throws exception
typeof ctx._source.anObject.anotherobject;

// using a custom typeof function...
var typeOf = function(v) {
  return (
    Object.prototype.toString.call(v).match(/\[object ([A-Za-z]+)\]/)[1].toLowerCase()
  );
};

typeOf(ctx._source.anObject.anotherobject); // returns 'nativemap'
typeOf(ctx._source.anObject.anArray); // returns 'nativelist'
```

I can convert to proper JS types by iterating the objects and copying the properties / values, but surely these should be converted when passing the doc source and script params to the scope? Might be related to the Rhino warning.

**Comment by dadoonet** [comment]
Sorry to come on this super late.
Did you fix it? Do you have a full example I can easily reproduce?

**Comment by sumitjainn** [comment]
Is someone working on this?

**Comment by dadoonet** [comment]
Closing as this plugin does not live here anymore and we recommend using painless instead.
