### ISSUE TITLE
Unable to mvn clean install off the es-1.5 branch

### ISSUE THREAD

**Issue by TimHeckel** [elastic/elasticsearch-lang-javascript#36]
I'm trying to build the plugin from source and am getting this issue:

`mvn clean install -U -DskipTests`

Results in the below

[INFO] Scanning for projects...
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-parent/1.5.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-parent/1.5.0-SNAPSHOT/elasticsearch-parent-1.5.0-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.elasticsearch:elasticsearch-lang-javascript:2.5.0-SNAPSHOT: Could not find artifact org.elasticsearch:elasticsearch-parent:pom:1.5.0-SNAPSHOT in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.elasticsearch:elasticsearch-lang-javascript:2.5.0-SNAPSHOT (/Users/tim/Projects/thirdparty/elasticsearch-lang-javascript/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.elasticsearch:elasticsearch-lang-javascript:2.5.0-SNAPSHOT: Could not find artifact org.elasticsearch:elasticsearch-parent:pom:1.5.0-SNAPSHOT in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by dadoonet** [comment]
Yes. We need to update and release this branch.
If you want to build a version by yourself, change 1.5.0-SNAPSHOT to 1.5.0 in pom.xml

**Comment by dadoonet** [comment]
Closed by #37.
