### ISSUE TITLE
Allow to check whether a document has a specific field

### ISSUE THREAD

**Issue by sol** [elastic/elasticsearch-lang-javascript#4]
If I try to access a field that is not present, I get an exception.  It would be great if there would be a way to check whether a document has a specific field, e.g. with

``` javascript
"some_field" in doc
```

**Comment by petrbela** [comment]
why can't you just do `if (doc.some_field)` ?

**Comment by hudlee** [comment]
Is this because objects that get passed in through params are of type java.util.HashMap instead of a proper javascript object? typeof doesn't work either. if (doc.some_field) or if (doc['some_field']) works fine.

**Comment by petrbela** [comment]
Something like that, based also on this: https://github.com/elastic/elasticsearch-lang-javascript/issues/26
I actually decided to rewrite our script in Groovy since JS support doesn't seem to be tested very well.

**Comment by jernejc** [comment]
Same issue, some objects come in as java.util.HashMap.
{Object here} "of class java.util.HashMap where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call."

**Comment by dadoonet** [comment]
Closing as this plugin does not live here anymore and we recommend using painless instead.
