### ISSUE TITLE
Missing methods for array params

### ISSUE THREAD

**Issue by dsernst** [elastic/elasticsearch-lang-javascript#42]
If I pass in an array like:

```js
script_file: 'myScript',
lang: 'javascript',
params: {
  myParam: [3, 4, 5]
}
```

Then trying any of these from within `myScript.js` will fail with a `has no method` error:

```
myParam.slice()
myParam.reduce()
myParam.push()
```

`reason: 'EcmaError[TypeError: Cannot find function slice in object [3, 4, 5]. (Script23.js#15)]' },`

**Comment by dadoonet** [comment]
This issue was moved to elastic/elasticsearch#13652
