### ISSUE TITLE
Unable to install js plugin in ES 2.0

### ISSUE THREAD

**Issue by sumitjainn** [elastic/elasticsearch-lang-javascript#43]
I get this error when installing

NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

checked the jar, it has es-plugin.properties file instead of plugin-descriptor.properties, is there some way to get it working

**Comment by clintongormley** [comment]
This plugin has moved to the core Elasticsearch repo in 2.0. You can install it with:  

    bin/plugin install lang-javascript
